name: Push Image to GHCR

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build -t ghcr.io/manumura/spring-kafka-demo:latest .

      - name: 'Push Image'
        run: |
          docker push ghcr.io/manumura/spring-kafka-demo:latest
